// <auto-generated />
using System;
using Consolidado.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Consolidado.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(ConsolidadoDbContext))]
    partial class ConsolidadoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Consolidado.Domain.SaldoDiario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<int>("QuantidadeCreditos")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeDebitos")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalCreditos")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalDebitos")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContaId", "Data")
                        .IsUnique();

                    b.ToTable("saldos_diarios", (string)null);
                });

            modelBuilder.Entity("Consolidado.Infrastructure.Idempotencia.MensagemProcessada", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ProcessadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MessageId");

                    b.ToTable("mensagens_processadas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
